### ISSUE TITLE
Get Feature Info

### ISSUE THREAD

**Issue by gHupf** [gHupf/GIS-Polimi-Group-3#12]
The GetFeatureInfo Popup appears even if the GlobeLand30 is not activated. This is pretty annoying since the user has no idea what it refers to and it appears on every click, even if you don't want it to appear.

Also if the GetFeatureInfo window is empty, the popup should not appear. It appears right now even if you click outside the GlobeLand30 raster.

**Comment by dumontgoulart** [comment]
done!

**Comment by gHupf** [comment]
Sorry, need to reopen it: We still need to expand the funcionality in a way, that the popup disappears of you drag the window or click somewhere else. Like it works for the points.

**Comment by gHupf** [comment]
Done
