### ISSUE TITLE
WMS globeland30 2010

### ISSUE THREAD

**Issue by dumontgoulart** [gHupf/GIS-Polimi-Group-3#4]
this website can help us putting the wms 

 https://gis.stackexchange.com/questions/283900/getting-wms-server-from-globeland30-landcover-interactive-map

**Comment by dumontgoulart** [comment]
To do this, I already did the popup part, now we have to finish with the WMS

**Comment by gHupf** [comment]
Not anymore needed, since we make our own WMS via Geoserver
