### ISSUE TITLE
General progress

### ISSUE THREAD

**Issue by dumontgoulart** [gHupf/GIS-Polimi-Group-3#5]
1 - [x ] three different basemaps

2 - [x] all the controls shown in practice

3 - [x] one WMS layer of GlobeLand30 of 2010 that upon clicking shows the
classification, (closing the popup missing)
4 - [x] all the points collected with the Land Cover Collector that can be queried. The
collected data is in JSON format. Import it in QGIS, export it as shapefile,
import it in GeoServer, use the data with WFS.

5 - [x] website with least two HTML pages

**Comment by dumontgoulart** [comment]
Shall we add Overlayers maps as well?

**Comment by gHupf** [comment]
Openstreetmap public transport does this. So we could add it possibly as another basemap

**Comment by dumontgoulart** [comment]
Set icon styles, different icons for different classes (like the app)

**Comment by gHupf** [comment]
Done! woopwoop
